version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/task_manager
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=task_manager.settings
      - DJANGO_DEBUG=True

  celery:
    build: .
    command: celery -A task_manager worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/task_manager
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=task_manager.settings
      - DJANGO_DEBUG=True

volumes:
  postgres_data: